### ISSUE TITLE
Spring boot application name not loaded

### ISSUE THREAD

**Issue by qzhou-hmcts** [hmcts/java-logging#92]
### What would you like to change?
Sometimes, depends on the order of the components be called,  SpringApplicationName value is not populated as this element is not loaded by spring context yet. Therefore  CloudRoleName won't be set as the value is not available. 
Application Insights Java SDK 2.3.0 now is integrated with Spring, any plan to update?
### How do you think that would improve the project?
Bug fix
### If this entry is related to a bug, please provide the steps to reproduce it
Create an app using Srping-Boot version 2.0.4

**Comment by timja** [comment]
Try using the spring boot starter directly and not the java-logging-appinsights

We haven't had time to fully evaluate it but multiple teams are doing that instead as far as i'm aware

**Comment by timja** [comment]
This is sorted by using the spring boot starter (included as a dep of this project) and I think a PR for that as well
